# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Vignesh\Software\Pythonscripts\Word_Finder\Word_Finder.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Word_Finder(object):
    def setupUi(self, Word_Finder):
        Word_Finder.setObjectName(_fromUtf8("Word_Finder"))
        Word_Finder.resize(800, 544)
        Word_Finder.setMinimumSize(QtCore.QSize(800, 530))
        Word_Finder.setMaximumSize(QtCore.QSize(800, 544))
        self.centralwidget = QtGui.QWidget(Word_Finder)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tab_FindReplace = QtGui.QTabWidget(self.centralwidget)
        self.tab_FindReplace.setMinimumSize(QtCore.QSize(780, 250))
        self.tab_FindReplace.setMaximumSize(QtCore.QSize(780, 250))
        self.tab_FindReplace.setObjectName(_fromUtf8("tab_FindReplace"))
        self.tab_Find = QtGui.QWidget()
        self.tab_Find.setObjectName(_fromUtf8("tab_Find"))
        self.l_find_what = QtGui.QLabel(self.tab_Find)
        self.l_find_what.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.l_find_what.setObjectName(_fromUtf8("l_find_what"))
        self.l_find_where = QtGui.QLabel(self.tab_Find)
        self.l_find_where.setGeometry(QtCore.QRect(30, 70, 71, 16))
        self.l_find_where.setObjectName(_fromUtf8("l_find_where"))
        self.bt_find = QtGui.QPushButton(self.tab_Find)
        self.bt_find.setGeometry(QtCore.QRect(630, 10, 111, 51))
        self.bt_find.setObjectName(_fromUtf8("bt_find"))
        self.bt_close = QtGui.QPushButton(self.tab_Find)
        self.bt_close.setGeometry(QtCore.QRect(630, 160, 111, 51))
        self.bt_close.setObjectName(_fromUtf8("bt_close"))
        self.l_find_filters = QtGui.QLabel(self.tab_Find)
        self.l_find_filters.setGeometry(QtCore.QRect(30, 110, 71, 20))
        self.l_find_filters.setObjectName(_fromUtf8("l_find_filters"))
        self.le_find_value = QtGui.QLineEdit(self.tab_Find)
        self.le_find_value.setGeometry(QtCore.QRect(120, 30, 381, 20))
        self.le_find_value.setObjectName(_fromUtf8("le_find_value"))
        self.le_location = QtGui.QLineEdit(self.tab_Find)
        self.le_location.setGeometry(QtCore.QRect(120, 70, 381, 20))
        self.le_location.setObjectName(_fromUtf8("le_location"))
        self.cb_find_filters = QtGui.QComboBox(self.tab_Find)
        self.cb_find_filters.setGeometry(QtCore.QRect(120, 110, 171, 22))
        self.cb_find_filters.setObjectName(_fromUtf8("cb_find_filters"))
        self.cb_find_filters.addItem(_fromUtf8(""))
        self.cb_find_filters.addItem(_fromUtf8(""))
        self.cb_find_filters.addItem(_fromUtf8(""))
        self.cb_find_filters.addItem(_fromUtf8(""))
        self.bt_file_dialog = QtGui.QPushButton(self.tab_Find)
        self.bt_file_dialog.setGeometry(QtCore.QRect(520, 70, 31, 23))
        self.bt_file_dialog.setObjectName(_fromUtf8("bt_file_dialog"))
        self.bt_find_all = QtGui.QPushButton(self.tab_Find)
        self.bt_find_all.setGeometry(QtCore.QRect(630, 80, 111, 51))
        self.bt_find_all.setObjectName(_fromUtf8("bt_find_all"))
        self.tab_FindReplace.addTab(self.tab_Find, _fromUtf8(""))
        self.tab_Replace = QtGui.QWidget()
        self.tab_Replace.setObjectName(_fromUtf8("tab_Replace"))
        self.le_replace_find_value = QtGui.QLineEdit(self.tab_Replace)
        self.le_replace_find_value.setGeometry(QtCore.QRect(120, 30, 381, 20))
        self.le_replace_find_value.setObjectName(_fromUtf8("le_replace_find_value"))
        self.l_replace_value = QtGui.QLabel(self.tab_Replace)
        self.l_replace_value.setGeometry(QtCore.QRect(30, 70, 71, 16))
        self.l_replace_value.setText(_fromUtf8(""))
        self.l_replace_value.setObjectName(_fromUtf8("l_replace_value"))
        self.cb_replace_filters = QtGui.QComboBox(self.tab_Replace)
        self.cb_replace_filters.setGeometry(QtCore.QRect(120, 150, 171, 22))
        self.cb_replace_filters.setObjectName(_fromUtf8("cb_replace_filters"))
        self.cb_replace_filters.addItem(_fromUtf8(""))
        self.cb_replace_filters.addItem(_fromUtf8(""))
        self.cb_replace_filters.addItem(_fromUtf8(""))
        self.cb_replace_filters.addItem(_fromUtf8(""))
        self.le_replace_location = QtGui.QLineEdit(self.tab_Replace)
        self.le_replace_location.setGeometry(QtCore.QRect(120, 110, 381, 20))
        self.le_replace_location.setObjectName(_fromUtf8("le_replace_location"))
        self.l_replace_find = QtGui.QLabel(self.tab_Replace)
        self.l_replace_find.setGeometry(QtCore.QRect(60, 30, 31, 20))
        self.l_replace_find.setObjectName(_fromUtf8("l_replace_find"))
        self.l_replace_file_filters = QtGui.QLabel(self.tab_Replace)
        self.l_replace_file_filters.setGeometry(QtCore.QRect(60, 150, 71, 20))
        self.l_replace_file_filters.setObjectName(_fromUtf8("l_replace_file_filters"))
        self.bt_replace_file_dialog = QtGui.QPushButton(self.tab_Replace)
        self.bt_replace_file_dialog.setGeometry(QtCore.QRect(510, 110, 31, 23))
        self.bt_replace_file_dialog.setObjectName(_fromUtf8("bt_replace_file_dialog"))
        self.le_replace_value = QtGui.QLineEdit(self.tab_Replace)
        self.le_replace_value.setGeometry(QtCore.QRect(120, 70, 381, 20))
        self.le_replace_value.setObjectName(_fromUtf8("le_replace_value"))
        self.l_replace = QtGui.QLabel(self.tab_Replace)
        self.l_replace.setGeometry(QtCore.QRect(60, 70, 51, 20))
        self.l_replace.setObjectName(_fromUtf8("l_replace"))
        self.l_replace_location = QtGui.QLabel(self.tab_Replace)
        self.l_replace_location.setGeometry(QtCore.QRect(60, 110, 51, 20))
        self.l_replace_location.setObjectName(_fromUtf8("l_replace_location"))
        self.bt_replace_find = QtGui.QPushButton(self.tab_Replace)
        self.bt_replace_find.setGeometry(QtCore.QRect(550, 10, 101, 31))
        self.bt_replace_find.setObjectName(_fromUtf8("bt_replace_find"))
        self.bt_replace_close = QtGui.QPushButton(self.tab_Replace)
        self.bt_replace_close.setGeometry(QtCore.QRect(660, 180, 101, 31))
        self.bt_replace_close.setObjectName(_fromUtf8("bt_replace_close"))
        self.bt_replace_find_all = QtGui.QPushButton(self.tab_Replace)
        self.bt_replace_find_all.setGeometry(QtCore.QRect(660, 10, 101, 31))
        self.bt_replace_find_all.setObjectName(_fromUtf8("bt_replace_find_all"))
        self.gb_Replace_Options = QtGui.QGroupBox(self.tab_Replace)
        self.gb_Replace_Options.setGeometry(QtCore.QRect(560, 60, 201, 101))
        self.gb_Replace_Options.setObjectName(_fromUtf8("gb_Replace_Options"))
        self.rb_allinFile = QtGui.QRadioButton(self.gb_Replace_Options)
        self.rb_allinFile.setGeometry(QtCore.QRect(10, 20, 151, 17))
        self.rb_allinFile.setObjectName(_fromUtf8("rb_allinFile"))
        self.rb_selinFile = QtGui.QRadioButton(self.gb_Replace_Options)
        self.rb_selinFile.setGeometry(QtCore.QRect(10, 40, 191, 17))
        self.rb_selinFile.setObjectName(_fromUtf8("rb_selinFile"))
        self.rb_allinFiles = QtGui.QRadioButton(self.gb_Replace_Options)
        self.rb_allinFiles.setGeometry(QtCore.QRect(10, 60, 181, 17))
        self.rb_allinFiles.setObjectName(_fromUtf8("rb_allinFiles"))
        self.rb_selinfiles = QtGui.QRadioButton(self.gb_Replace_Options)
        self.rb_selinfiles.setGeometry(QtCore.QRect(10, 80, 191, 17))
        self.rb_selinfiles.setObjectName(_fromUtf8("rb_selinfiles"))
        self.bt_replace = QtGui.QPushButton(self.tab_Replace)
        self.bt_replace.setGeometry(QtCore.QRect(550, 180, 101, 31))
        self.bt_replace.setObjectName(_fromUtf8("bt_replace"))
        self.tab_FindReplace.addTab(self.tab_Replace, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_FindReplace)
        self.table_Results = QtGui.QTableWidget(self.centralwidget)
        self.table_Results.setMinimumSize(QtCore.QSize(779, 250))
        self.table_Results.setMaximumSize(QtCore.QSize(780, 250))
        self.table_Results.setColumnCount(5)
        self.table_Results.setObjectName(_fromUtf8("table_Results"))
        self.table_Results.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_Results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_Results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_Results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_Results.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_Results.setHorizontalHeaderItem(4, item)
        self.table_Results.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.table_Results)
        Word_Finder.setCentralWidget(self.centralwidget)
        self.WordFinder_Status = QtGui.QStatusBar(Word_Finder)
        self.WordFinder_Status.setObjectName(_fromUtf8("WordFinder_Status"))
        Word_Finder.setStatusBar(self.WordFinder_Status)
        self.action_Settings = QtGui.QAction(Word_Finder)
        self.action_Settings.setObjectName(_fromUtf8("action_Settings"))

        self.retranslateUi(Word_Finder)
        self.tab_FindReplace.setCurrentIndex(0)
        QtCore.QObject.connect(self.bt_close, QtCore.SIGNAL(_fromUtf8("clicked()")), Word_Finder.close)
        QtCore.QObject.connect(self.bt_replace_close, QtCore.SIGNAL(_fromUtf8("clicked()")), Word_Finder.close)
        QtCore.QMetaObject.connectSlotsByName(Word_Finder)

    def retranslateUi(self, Word_Finder):
        Word_Finder.setWindowTitle(_translate("Word_Finder", "Word Finder", None))
        self.l_find_what.setText(_translate("Word_Finder", "Find What:", None))
        self.l_find_where.setText(_translate("Word_Finder", "Find Where:", None))
        self.bt_find.setText(_translate("Word_Finder", "FIND", None))
        self.bt_close.setText(_translate("Word_Finder", "CLOSE", None))
        self.l_find_filters.setText(_translate("Word_Finder", "File Filters:", None))
        self.cb_find_filters.setItemText(0, _translate("Word_Finder", "All Files", None))
        self.cb_find_filters.setItemText(1, _translate("Word_Finder", "Text Files (*.txt)", None))
        self.cb_find_filters.setItemText(2, _translate("Word_Finder", "Microsoft Office (*.doc,*.docx,*.xls,*.xlsm,*.ppt,*.pptx,...)", None))
        self.cb_find_filters.setItemText(3, _translate("Word_Finder", "Open Office (*.odt,*.ods,*.odp,*.odg,*.odf,...)", None))
        self.bt_file_dialog.setText(_translate("Word_Finder", "...", None))
        self.bt_find_all.setText(_translate("Word_Finder", "FIND ALL", None))
        self.tab_FindReplace.setTabText(self.tab_FindReplace.indexOf(self.tab_Find), _translate("Word_Finder", "Find", None))
        self.cb_replace_filters.setItemText(0, _translate("Word_Finder", "All Files", None))
        self.cb_replace_filters.setItemText(1, _translate("Word_Finder", "Text Files (*.txt)", None))
        self.cb_replace_filters.setItemText(2, _translate("Word_Finder", "Microsoft Office (*.doc,*.docx,*.xls,*.xlsm,*.ppt,*.pptx,...)", None))
        self.cb_replace_filters.setItemText(3, _translate("Word_Finder", "Open Office (*.odt,*.ods,*.odp,*.odg,*.odf,...)", None))
        self.l_replace_find.setText(_translate("Word_Finder", "Find :", None))
        self.l_replace_file_filters.setText(_translate("Word_Finder", "File Filters:", None))
        self.bt_replace_file_dialog.setText(_translate("Word_Finder", "...", None))
        self.l_replace.setText(_translate("Word_Finder", "Replace :", None))
        self.l_replace_location.setText(_translate("Word_Finder", "Location:", None))
        self.bt_replace_find.setText(_translate("Word_Finder", "FIND", None))
        self.bt_replace_close.setText(_translate("Word_Finder", "CLOSE", None))
        self.bt_replace_find_all.setText(_translate("Word_Finder", "FIND ALL", None))
        self.gb_Replace_Options.setTitle(_translate("Word_Finder", "Replace Options", None))
        self.rb_allinFile.setText(_translate("Word_Finder", "All in Selected File", None))
        self.rb_selinFile.setText(_translate("Word_Finder", "Selected Instance in Selected File", None))
        self.rb_allinFiles.setText(_translate("Word_Finder", "All in Selected Files", None))
        self.rb_selinfiles.setText(_translate("Word_Finder", "Selected Instance in Selected Files", None))
        self.bt_replace.setText(_translate("Word_Finder", "REPLACE", None))
        self.tab_FindReplace.setTabText(self.tab_FindReplace.indexOf(self.tab_Replace), _translate("Word_Finder", "Replace", None))
        item = self.table_Results.horizontalHeaderItem(0)
        item.setText(_translate("Word_Finder", "File Name", None))
        item = self.table_Results.horizontalHeaderItem(1)
        item.setText(_translate("Word_Finder", "File Path", None))
        item = self.table_Results.horizontalHeaderItem(2)
        item.setText(_translate("Word_Finder", "Row Number", None))
        item = self.table_Results.horizontalHeaderItem(3)
        item.setText(_translate("Word_Finder", "Column Number", None))
        item = self.table_Results.horizontalHeaderItem(4)
        item.setText(_translate("Word_Finder", "Line", None))
        self.action_Settings.setText(_translate("Word_Finder", "&Settings", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Word_Finder = QtGui.QMainWindow()
    ui = Ui_Word_Finder()
    ui.setupUi(Word_Finder)
    Word_Finder.show()
    sys.exit(app.exec_())

